In [12]:
import numpy as np

grid = np.array([
    [ 1,  2,  3,  4,  5],
    [ 6,  7,  8,  9, 10],
    [11, 12, 13, 14, 15],
    [16, 17, 18, 19, 20]
])

# (a) Get the value 13 using row/column indexing
print(grid[2, 2])

# (b) Get the entire 3rd row ([11, 12, 13, 14, 15])
print(grid[2, :])

# (c) Get the entire last column ([5, 10, 15, 20])
print(grid[:, -1])

# (d) Get the sub-grid containing just rows 1–2 and columns 1–3 (should output [[7, 8, 9], [12, 13, 14]])
print(grid[1:3, 1:4])

# (e) Take a slice of the first row, modify an element in the slice, and prove to yourself it's a view (i.e., show that the original grid also changed)
first_row = grid[0, :]
first_row[2] = 30
print(grid[0, :])

13
[11 12 13 14 15]
[ 5 10 15 20]
[[ 7  8  9]
 [12 13 14]]
[ 1  2 30  4  5]
